# Generated by Django 4.0.3 on 2022-04-10 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 1, 58, 9, 133036)),
            preserve_default=False,
        ),
    ]
